ccflags-y += -I$(srctree)/kernel/nanokernel/include
ccflags-y +=-I$(srctree)/arch/$(ARCH)/include
ccflags-y += -I$(srctree)/kernel/microkernel/include

obj-y += atomic.o cpu_idle.o fatal.o gptimers.o \
	irq_manage.o swap.o thread.o memaccess.o
