${RTL_HOME}/techmap/bufg/ibufg_tech.sv
${RTL_HOME}/techmap/bufg/ibuf_tech.sv
${RTL_HOME}/techmap/bufg/idsbuf_tech.sv
${RTL_HOME}/techmap/bufg/igdsbuf_tech.sv
${RTL_HOME}/techmap/bufg/iobuf_tech.sv
${RTL_HOME}/techmap/bufg/obuf_tech.sv
${RTL_HOME}/techmap/mem/ram_cache_bwe_tech.sv
${RTL_HOME}/techmap/mem/ram_mmu_tech.sv
${RTL_HOME}/techmap/mem/srambytes_tech.sv
${RTL_HOME}/techmap/mem/ram_inferred.sv
${RTL_HOME}/techmap/mem/ram_fpga_distr.sv
${RTL_HOME}/techmap/mem/ram_tech.sv
${RTL_HOME}/techmap/mem/rom_inferred_32.sv
${RTL_HOME}/techmap/mem/rom_inferred_2x32.sv
${RTL_HOME}/techmap/mem/rom_tech.sv
${RTL_HOME}/techmap/pll/SysPLL_tech.sv
${RTL_HOME}/techmap/cdc_axi_sync/kc705/axi_clock_converter_v2_1_vl_rfs.v
${RTL_HOME}/techmap/cdc_axi_sync/kc705/axi_infrastructure_v1_1_vl_rfs.v
${RTL_HOME}/techmap/cdc_axi_sync/kc705/cdc_ddr.v
${RTL_HOME}/techmap/cdc_axi_sync/cdc_axi_sync_tech.v
${RTL_HOME}/techmap/ddr/ddr_inferred.sv
${RTL_HOME}/techmap/ddr/ddr_kc705.sv
${RTL_HOME}/techmap/ddr/ddr_tech.sv
