
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:29:51 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'rocket_soc.ucf'
####################################################################################


# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent


create_clock -name i_sclk_p -period 5.000 [get_ports i_sclk_p]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'i_sclk_p' has been applied to the port object 'i_sclk_p'.
set_property IOSTANDARD LVDS [get_ports i_sclk_p]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'i_sclk_n' has been applied to the port object 'i_sclk_n'.
set_property IOSTANDARD LVDS [get_ports i_sclk_n]
set_property PACKAGE_PIN AD12 [get_ports i_sclk_p]
set_property PACKAGE_PIN AD11 [get_ports i_sclk_n]

# button "Center"
set_property PACKAGE_PIN G12 [get_ports i_rst]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets i_rst]

set_property PACKAGE_PIN AF22 [get_ports i_clk_adc]
# DIP switch: SW1.1
set_property PACKAGE_PIN Y29 [get_ports {i_dip[0]}]
set_property PACKAGE_PIN W29 [get_ports {i_dip[1]}]
set_property PACKAGE_PIN AA28 [get_ports {i_dip[2]}]
set_property PACKAGE_PIN Y28 [get_ports {i_dip[3]}]



#UART interface
set_property PACKAGE_PIN K23 [get_ports i_uart1_ctsn]
set_property PACKAGE_PIN M19 [get_ports i_uart1_rd]
set_property PACKAGE_PIN L27 [get_ports o_uart1_rtsn]
set_property PACKAGE_PIN K24 [get_ports o_uart1_td]


#/ User's LEDs:
set_property PACKAGE_PIN AB8 [get_ports {o_led[0]}]
set_property PACKAGE_PIN AA8 [get_ports {o_led[1]}]
set_property PACKAGE_PIN AC9 [get_ports {o_led[2]}]
set_property PACKAGE_PIN AB9 [get_ports {o_led[3]}]
set_property PACKAGE_PIN AE26 [get_ports {o_led[4]}]
set_property PACKAGE_PIN G19 [get_ports {o_led[5]}]
set_property PACKAGE_PIN E18 [get_ports {o_led[6]}]
set_property PACKAGE_PIN F16 [get_ports {o_led[7]}]


# The conversion of 'IOSTANDARD' constraint on 'net' object 'i_clk_adc' has been applied to the port object 'i_clk_adc'.
set_property IOSTANDARD LVCMOS25 [get_ports i_clk_adc]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'i_uart1_ctsn' has been applied to the port object 'i_uart1_ctsn'.
set_property IOSTANDARD LVCMOS25 [get_ports i_uart1_ctsn]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'i_dip[0]' has been applied to the port object 'i_dip[0]'.
set_property IOSTANDARD LVCMOS25 [get_ports {i_dip[0]}]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'i_dip[1]' has been applied to the port object 'i_dip[1]'.
set_property IOSTANDARD LVCMOS25 [get_ports {i_dip[1]}]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'i_dip[2]' has been applied to the port object 'i_dip[2]'.
set_property IOSTANDARD LVCMOS25 [get_ports {i_dip[2]}]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'i_dip[3]' has been applied to the port object 'i_dip[3]'.
set_property IOSTANDARD LVCMOS25 [get_ports {i_dip[3]}]


# The conversion of 'IOSTANDARD' constraint on 'net' object 'i_uart1_rd' has been applied to the port object 'i_uart1_rd'.
set_property IOSTANDARD LVCMOS25 [get_ports i_uart1_rd]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'i_rst' has been applied to the port object 'i_rst'.
set_property IOSTANDARD LVCMOS25 [get_ports i_rst]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'o_led[0]' has been applied to the port object 'o_led[0]'.
set_property IOSTANDARD LVCMOS15 [get_ports {o_led[0]}]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'o_led[1]' has been applied to the port object 'o_led[1]'.
set_property IOSTANDARD LVCMOS15 [get_ports {o_led[1]}]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'o_led[2]' has been applied to the port object 'o_led[2]'.
set_property IOSTANDARD LVCMOS15 [get_ports {o_led[2]}]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'o_led[3]' has been applied to the port object 'o_led[3]'.
set_property IOSTANDARD LVCMOS15 [get_ports {o_led[3]}]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'o_led[4]' has been applied to the port object 'o_led[4]'.
set_property IOSTANDARD LVCMOS25 [get_ports {o_led[4]}]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'o_led[5]' has been applied to the port object 'o_led[5]'.
set_property IOSTANDARD LVCMOS25 [get_ports {o_led[5]}]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'o_led[6]' has been applied to the port object 'o_led[6]'.
set_property IOSTANDARD LVCMOS25 [get_ports {o_led[6]}]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'o_led[7]' has been applied to the port object 'o_led[7]'.
set_property IOSTANDARD LVCMOS25 [get_ports {o_led[7]}]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'o_uart1_rtsn' has been applied to the port object 'o_uart1_rtsn'.
set_property IOSTANDARD LVCMOS25 [get_ports o_uart1_rtsn]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'o_uart1_td' has been applied to the port object 'o_uart1_td'.
set_property IOSTANDARD LVCMOS25 [get_ports o_uart1_td]

# new tap controller
# comment this if using xilinx tap
# ahbjtag.vhd line 107:
# tech => tech (xilinx tap)
# tech => 0 (asic tap)
#NET "TMS" LOC = AE21;
#NET "TMS" IOSTANDARD = LVCMOS25;
#NET "TCK" LOC = AD21;
#NET "TCK" IOSTANDARD = LVCMOS25;
#NET "TDO" LOC = AK25;
#NET "TDO" IOSTANDARD = LVCMOS25;
#NET "TDI" LOC = AJ24;
#NET "TDI" IOSTANDARD = LVCMOS25;
#NET "TCK" CLOCK_DEDICATED_ROUTE = FALSE;
