name: build
on:
    push:
    pull_request:
    workflow_dispatch:

env:
    CI_OS_NAME: linux
    CI_COMMIT: ${{ github.sha }}
    CCACHE_COMPRESS: 1
    CCACHE_DIR: ${{ github.workspace }}/.ccache
    CCACHE_LIMIT_MULTIPLE: 0.95
    QT_VERSION: 6.2.*

defaults:
    run:
        shell: bash
        working-directory: repo

jobs:
    build:
        name: Linux GCC
        runs-on: ubuntu-22.04
        env:
            CC: gcc-12
            CXX: g++-12
            CACHE_BASE_KEY: build-ubuntu-22.04-gcc-12
            CCACHE_MAXSIZE: 250M # Per build matrix entry (2000M in total)
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  path: repo  

            - name: Cache $CCACHE_DIR
              uses: actions/cache@v3
              env:
                 CACHE_KEY: ${{ env.CACHE_BASE_KEY }}-ccache
              with:
                 path: ${{ env.CCACHE_DIR }}
                 key: ${{ env.CACHE_KEY }}-${{ github.sha }}
                 restore-keys: |
                    ${{ env.CACHE_KEY }}-

            - name: Install Linux packages for build
              run: |
                  sudo apt-get update
                  sudo apt-get install -y ccache g++-12 libstdc++-12-dev cmake

            - name: Download and build latest SystemC (3.0.1)
              run: |
                  SYSTEMC_VERSION=3.0.1
                  wget https://github.com/accellera-official/systemc/archive/refs/tags/${SYSTEMC_VERSION}.tar.gz
                  tar -xzf ${SYSTEMC_VERSION}.tar.gz
                  cd systemc-${SYSTEMC_VERSION}
                  mkdir -p objdir
                  cd objdir
                  export CXXFLAGS="-std=c++17"
                  ../configure --prefix=$HOME/systemc --enable-pthreads
                  make -j$(nproc)
                  make install

            - name: Install Qt6
              uses: jurplel/install-qt-action@v3
              with:
                version: ${{env.QT_VERSION}}
                host:    linux
                dir:     $RUNNER_TEMP
                modules: qtscxml

            - name: Build 
              run: /bin/bash .ci/build-project.sh
              env:
                QT_PATH: ${{github.workspace}}/${{env.Qt6_DIR}}
                SYSTEMC_SRC: $HOME/systemc/include
                SYSTEMC_LIB: $HOME/systemc/lib-linux64

